version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: SDSC5003
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3366:3306"
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdsc5003-app
    restart: always
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@mysql:3306/SDSC5003"
      JWT_SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    ports:
      - "8000:8000"
    depends_on:
      - mysql
